extends Node

enum {
	
	PARTICLE_EFFECTS_BELOW_ENEMIES = -111
	ENEMIES = -110
	
	TOWER_BENCH = -100,
	TOWER_PLACABLES = -98,
	
	TOWERS = -90,
	
	PARTICLE_EFFECTS = -80
	SCREEN_EFFECTS = -70
	
	TOWERS_BEING_DRAGGED = 2,
	
	SCREEN_EFFECTS_ABOVE_ALL = VisualServer.CANVAS_ITEM_Z_MAX - 1
	WHOLE_SCREEN_GUI = VisualServer.CANVAS_ITEM_Z_MAX
}
